source 'https://rubygems.org'

gem 'rake'
gem 'opal',           :github => 'opal/opal'
gem 'opal-jquery',    :github => 'opal/opal-jquery'
# gem 'vienna',         :github => 'opal/vienna'
gem 'vienna',         :path => '../vienna'
gem 'opal-haml',      :github => 'opal/opal-haml'
gem 'opal-rspec',     '0.3.0.beta2'
gem 'thin'
